version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - /home/pika/Config/docker/volumes/jellyfin_config:/config
      - /home/pika/Config/docker/volumes/jellyfin_cache:/cache
      - type: bind
        source: /mnt/hdd/Media
        target: /media
      - type: bind
        source: /mnt/hdd2/Media
        target: /media2
    restart: always
