#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '
alias build-config='cargo run --manifest-path /home/pika/Software/config-king/Cargo.toml -- directory=/home/pika/Config/config.lua'
alias edit='cd /home/pika/Config'
alias vi="nvim"
